# frozen_string_literal: true
#==============================================================================
# Copyright (C) 2021-present Alces Flight Ltd.
#
# This file is part of Flight Job Script Service.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight Job Script Service is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight Job Script Service. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on Flight Job Script Service, please visit:
# https://github.com/openflighthpc/flight-job-script-service
#==============================================================================
source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'activemodel', require: 'active_model'
gem 'activesupport', require: 'active_support'
gem 'flight_auth', github: "openflighthpc/flight_auth", branch: "297cb7241b820d334e5d593c4e237a81b83a9995"
gem 'flight_configuration', github: 'openflighthpc/flight_configuration', branch: 'c4801f554cbba88c019c63cae242667764f7db5e'
gem 'concurrent-ruby'
gem 'json_schemer'
gem 'rack-parser', require: 'rack/parser'
gem 'rake'
gem 'jwt'
gem 'puma'
gem 'sinatra', require: 'sinatra/base'
gem 'sinja', '~> 1.3'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
end

group :test do
  gem 'factory_bot'
  gem 'fakefs', require: 'fakefs/spec_helpers'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-collection_matchers'
end
